-- =============================================================================
-- 注意: `projects.id` が整数型（serial）の場合、このファイルは**使わない**でください。
-- UUID 二重運用は `migrate-projects-add-id-uuid.sql` + `id_uuid` 列を参照してください。
-- =============================================================================
-- 以下は「projects.id が uuid 型」のスキーマ向けの古いメモ用です。
-- ALTER TABLE public.projects
--   ALTER COLUMN id SET DEFAULT gen_random_uuid();
