-- Creating the transactions ledger table for decoupled financial tracking
CREATE TABLE IF NOT EXISTS public.transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT REFERENCES public.projects(id) ON DELETE CASCADE,
    type TEXT NOT NULL,
    category TEXT,
    title TEXT,
    amount NUMERIC DEFAULT 0,
    date TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE
);

-- Enable RLS
ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;

-- Create policy for authenticated user access
CREATE POLICY "Enable ALL for users based on user_id" ON "public"."transactions"
AS PERMISSIVE FOR ALL
TO public
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

-- Create policy for Bypass context (Phantom Data)
CREATE POLICY "Enable ALL for Bypass (user_id IS NULL)" ON "public"."transactions"
AS PERMISSIVE FOR ALL
TO public
USING (user_id IS NULL)
WITH CHECK (user_id IS NULL);
